In [1]:
import cv2
import numpy as np
from PIL import Image
def imshow(img):
    return Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

Pnet 模型输出情况

In [58]:
pnet_ = cv2.dnn.readNetFromCaffe("/Users/yh-mac/Desktop/face/det1.prototxt", "/Users/yh-mac/Desktop/face/det1.caffemodel")
min_size = 40
threshold = [0.7, 0.6, 0.6]
factor = 0.709
std_val = 0.0078125
mean_val = 127.5

In [7]:
img = cv2.imread('../imgs/by.jpg')
# imshow(img)

In [22]:
inputBlob = cv2.dnn.blobFromImage(img, scalefactor=std_val, mean=[mean_val, mean_val, mean_val])
print('inputBlob: ', inputBlob.shape)
pnet_.setInput(inputBlob)
# 这边为什么输入
prob, reg = pnet_.forward(["prob1", "conv4-2"])
print('prob: ', prob.shape)
print('reg: ', reg.shape)
feature_map_w_ = prob.shape[3]
feature_map_h_ = prob.shape[2]
print('feature_map_w_:{}, feature_map_h_:{}'.format(feature_map_w_, feature_map_h_))
spatical_size = feature_map_w_ * feature_map_h_
print('spatical_size: ', spatical_size)
confidence_data = prob.reshape(-1)
print("confidence_data: ", confidence_data.shape)
reg_data = reg.reshape(-1)
print("reg_data: ", reg_data.shape)

inputBlob:  (1, 3, 358, 449)
prob:  (1, 2, 174, 220)
reg:  (1, 4, 174, 220)
feature_map_w_:220, feature_map_h_:174
spatical_size:  38280
confidence_data:  (76560,)
reg_data:  (153120,)


In [9]:
confidence_data

array([9.9972671e-01, 9.9965787e-01, 9.9972230e-01, ..., 1.7738843e-04,
       2.9242563e-04, 6.1534526e-04], dtype=float32)

In [11]:
for i in range(0, spatical_size):
    if confidence_data[i] >= 0.7:
        y = i // feature_map_w_
        x = i - feature_map_w_ * y
        x1 = x * 2
        y1 = y * 2
        x2 = x * 2 + 12
        y2 = y * 2 + 12
        box = [x1, y1, x2, y2]
        reg_x1 = reg_data[i]
        reg_y1 = reg_data[i + spatical_size]
        reg_x2 = reg_data[i + 2 + spatical_size]
        reg_y2 = reg_data[i + 3 + spatical_size]
        reg_box = [reg_x1, reg_y1, reg_x2, reg_y2]
        score = confidence_data[i]
#         print(box, reg_box, score)
#         cv2.rectangle()
        

In [42]:
# feature_map_w_ = prob[3]
# feature_map_h_ = prob[2]
# print('feature_map_w_:{}, feature_map_h_:{}'.format(feature_map_w_, feature_map_h_))

In [31]:
res[0][0].shape

(174, 220)

In [63]:
?pnet_.forward

In [19]:
reg

array([[[[ 0.0849082 , -0.00856221, -0.01316941, ..., -0.01972723,
          -0.01799428, -0.05145954],
         [ 0.08517995, -0.00997609, -0.01325747, ..., -0.02068305,
          -0.01717228, -0.05057696],
         [ 0.08464805, -0.00854144, -0.0149107 , ..., -0.0196695 ,
          -0.01869239, -0.05016108],
         ...,
         [ 0.08726424, -0.00038525,  0.00108975, ..., -0.002307  ,
          -0.00184684, -0.04309982],
         [ 0.0883468 , -0.00045159,  0.00103056, ..., -0.00576164,
          -0.00430748, -0.04264739],
         [ 0.09077533,  0.00114372, -0.00056577, ..., -0.00606124,
          -0.0067139 , -0.0435473 ]],

        [[-0.12147281, -0.13604411, -0.14084199, ..., -0.12324157,
          -0.11680108, -0.04465208],
         [-0.12467775, -0.13754833, -0.14083573, ..., -0.13586336,
          -0.1253472 , -0.04744706],
         [-0.12222944, -0.13702181, -0.14189976, ..., -0.14181852,
          -0.12964186, -0.04921512],
         ...,
         [-0.09577212, -0.10156432

In [26]:
tprob = prob[0][1]
tprob.shape

(174, 220)

In [49]:
treg = reg[0]
treg[3]

array([[0.08225402, 0.10640509, 0.10983014, ..., 0.13632521, 0.12647316,
        0.15277722],
       [0.07872733, 0.10360992, 0.10776892, ..., 0.12687919, 0.12020229,
        0.1504606 ],
       [0.08233659, 0.10171637, 0.10538924, ..., 0.11969057, 0.11900656,
        0.14984879],
       ...,
       [0.1046306 , 0.12980658, 0.12959762, ..., 0.11880618, 0.11435995,
        0.15153408],
       [0.10291684, 0.12996668, 0.12877986, ..., 0.12050611, 0.1169481 ,
        0.15173212],
       [0.0965867 , 0.12445781, 0.12368935, ..., 0.1239202 , 0.12151846,
        0.15590379]], dtype=float32)

In [131]:
index = np.where(tprob>0.9)

In [132]:
index

(array([ 90,  90,  90,  90, 109, 109, 111, 112, 112, 112, 113, 113, 113,
        114, 114, 114, 114, 114, 115, 115, 115, 115, 115, 115, 116, 116,
        116, 116, 116, 116, 116, 116, 117, 117, 128, 128, 129, 129, 129,
        129, 130, 130, 131, 131, 132, 133, 142, 143]),
 array([134, 135, 136, 137,  84,  88,  70,  88,  89,  90,  88,  89,  90,
         68,  69,  77,  78,  79,  68,  76,  77,  78,  79,  80,  62,  66,
         67,  68,  77,  78,  79,  80,  79,  80,  75,  95,  71,  79,  94,
         95,  71,  95,  81,  83,  83,  83, 107, 106]))

In [133]:
tprob[index]

array([0.9130377 , 0.9530508 , 0.9584734 , 0.9256229 , 0.9216092 ,
       0.94280124, 0.93973035, 0.99268794, 0.9798946 , 0.97398424,
       0.9842    , 0.97348636, 0.9681889 , 0.9107973 , 0.9241663 ,
       0.9688664 , 0.95793414, 0.9025884 , 0.96604043, 0.9217502 ,
       0.997968  , 0.9922841 , 0.9818288 , 0.9279692 , 0.9278703 ,
       0.94642013, 0.9156761 , 0.971817  , 0.97174406, 0.9768857 ,
       0.9424804 , 0.9360834 , 0.9130188 , 0.917077  , 0.9287472 ,
       0.90798026, 0.95339704, 0.9122147 , 0.9253573 , 0.9456234 ,
       0.9070695 , 0.9328472 , 0.9406743 , 0.9330493 , 0.9574915 ,
       0.9596093 , 0.902824  , 0.90708315], dtype=float32)

In [182]:
treg[1][index]

array([-0.0262881 ,  0.00172904, -0.01608828, -0.03088226,  0.08064966,
        0.01614984,  0.20108889,  0.0670848 ,  0.05078433,  0.05533332,
       -0.00084484, -0.04901923, -0.053419  ,  0.0824348 ,  0.00905333,
        0.06074748,  0.040008  ,  0.05416057,  0.05482019, -0.03019863,
        0.01340681, -0.00066402, -0.00101134,  0.0022533 , -0.03546332,
       -0.07378221, -0.04894128, -0.08521652, -0.0889061 , -0.04482935,
       -0.04189251, -0.09309165, -0.10850094, -0.10733675, -0.10867825,
        0.05925849, -0.03105323, -0.08820401,  0.0201842 , -0.0026305 ,
       -0.12167478, -0.06951687, -0.08629091,  0.10406767, -0.04149894,
       -0.21965978,  0.03761139,  0.00996434], dtype=float32)

In [183]:
index

(array([ 90,  90,  90,  90, 109, 109, 111, 112, 112, 112, 113, 113, 113,
        114, 114, 114, 114, 114, 115, 115, 115, 115, 115, 115, 116, 116,
        116, 116, 116, 116, 116, 116, 117, 117, 128, 128, 129, 129, 129,
        129, 130, 130, 131, 131, 132, 133, 142, 143]),
 array([134, 135, 136, 137,  84,  88,  70,  88,  89,  90,  88,  89,  90,
         68,  69,  77,  78,  79,  68,  76,  77,  78,  79,  80,  62,  66,
         67,  68,  77,  78,  79,  80,  79,  80,  75,  95,  71,  79,  94,
         95,  71,  95,  81,  83,  83,  83, 107, 106]))

In [189]:
feature_map_points = np.asarray(index)
feature_map_points

array([[ 90,  90,  90,  90, 109, 109, 111, 112, 112, 112, 113, 113, 113,
        114, 114, 114, 114, 114, 115, 115, 115, 115, 115, 115, 116, 116,
        116, 116, 116, 116, 116, 116, 117, 117, 128, 128, 129, 129, 129,
        129, 130, 130, 131, 131, 132, 133, 142, 143],
       [134, 135, 136, 137,  84,  88,  70,  88,  89,  90,  88,  89,  90,
         68,  69,  77,  78,  79,  68,  76,  77,  78,  79,  80,  62,  66,
         67,  68,  77,  78,  79,  80,  79,  80,  75,  95,  71,  79,  94,
         95,  71,  95,  81,  83,  83,  83, 107, 106]])

In [195]:
feature_map_points.T[:, 0]

array([ 90,  90,  90,  90, 109, 109, 111, 112, 112, 112, 113, 113, 113,
       114, 114, 114, 114, 114, 115, 115, 115, 115, 115, 115, 116, 116,
       116, 116, 116, 116, 116, 116, 117, 117, 128, 128, 129, 129, 129,
       129, 130, 130, 131, 131, 132, 133, 142, 143])

In [2]:
bboxes = np.load('/Users/yh-mac/Desktop/test.npy')
bboxes.shape

(5, 167)

In [22]:
bboxes[1:,:]

array([[ 2.27013014e+02,  9.49945662e+01,  3.39524035e+02,
         2.42670632e+02,  1.91048691e+02,  3.35462755e+02,
         2.54169334e+02,  3.13771379e+02,  1.11461103e+01,
         2.60761861e+02,  4.42503946e+02,  1.03524443e+02,
         2.54363729e+02,  2.97717666e+02,  3.16785415e+02,
         1.90409490e+02,  3.03290563e+02,  2.24818730e+02,
         3.51831786e+02,  2.59359799e+01,  2.60290360e+02,
         2.56473326e+02,  3.33073427e+02,  2.91585382e+02,
         1.23512457e+02,  1.93275087e+01,  9.62199593e+01,
         8.51312972e+00,  3.43180192e+02,  1.33920849e+02,
         8.35727460e+01,  2.54722444e+02,  1.66128128e+02,
         1.61520806e+02,  3.25730892e+02,  3.27601104e+02,
         1.00640035e+02,  3.96031005e+01,  1.71401664e+02,
         1.87465553e+02,  2.98075741e+02,  9.53594725e+01,
         2.45951312e+02,  2.68873787e+02,  2.77810141e+02,
         1.07650536e+02,  3.72209442e+02,  2.27795815e+02,
         2.15055436e+01,  4.12461911e+01,  6.42003213e+0

In [31]:
elems = np.ones((4, 4))
elems

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
rand = np.random.random(size=(4, 4))*2
rand

array([[0.98777632, 1.42297879, 1.51647298, 1.34867947],
       [1.77214631, 0.07493916, 1.22072238, 1.65962526],
       [0.67990079, 0.91491048, 0.4940299 , 1.23013072],
       [1.58966332, 0.48294975, 0.29495249, 1.0931375 ]])

In [42]:
np.maximum(elems, rand)

array([[1.        , 1.42297879, 1.51647298, 1.34867947],
       [1.77214631, 1.        , 1.22072238, 1.65962526],
       [1.        , 1.        , 1.        , 1.23013072],
       [1.58966332, 1.        , 1.        , 1.0931375 ]])

In [55]:
one = np.asarray(list(range(1, 31))).reshape(3, 10)
one

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [57]:
one.reshape(3, 5, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [51]:
one.reshape(-1, 5, 3).shape

(2, 5, 3)

In [48]:
one.shape

(10, 2)

In [26]:
one.shape

(2, 10, 2)

In [35]:
x = np.asarray([[22, 55], [44, 110]])
x = x.reshape(1, 2, 2)

ValueError: operands could not be broadcast together with shapes (1,2,2) (2,10,2) 

In [59]:
onet = cv2.dnn.readNetFromCaffe("/Users/yh-mac/Desktop/face/det3-half.prototxt", "/Users/yh-mac/Desktop/face/det3-half.caffemodel")

In [64]:
img = cv2.imread('/Users/yh-mac/my_project/cpp_implentation_research/imgs/1-p.jpg')

In [65]:
blob = cv2.dnn.blobFromImage(img, scalefactor=std_val, mean=[mean_val, mean_val, mean_val])

In [66]:
onet.setInput(blob)
reg_box, landmark , conf = onet.forward(["conv6-2", "conv6-3", "prob1"])

In [67]:
conf


array([[0.6435921 , 0.35640788]], dtype=float32)